LABELS = {
    "ai": (
        "AI-Generated / Likely AI\n\n"
        "Our automated detection system found strong indicators that this content "
        "may have been generated by AI rather than written by a human. Multiple "
        "analysis signals — including writing style patterns and text structure — "
        "suggest AI authorship. This label reflects our system's assessment, not a "
        "final determination. The creator may contest this classification."
    ),
    "human": (
        "Human-Written / Likely Human\n\n"
        "Our automated detection system found strong indicators that this content "
        "was written by a human. Multiple analysis signals — including vocabulary "
        "diversity, sentence rhythm, and stylistic patterns — suggest human "
        "authorship. This label reflects our system's assessment, not a guarantee. "
        "While we are confident in this result, no automated system is perfect."
    ),
    "uncertain": (
        "Uncertain Attribution\n\n"
        "Our system couldn't determine with confidence whether this content was "
        "written by a human or generated by AI. The writing shows a mix of patterns "
        "— some characteristic of human authorship, some of AI generation. We "
        "display this label transparently rather than guessing. The creator may "
        "contest this classification."
    ),
}


def get_label(attribution: str) -> str:
    return LABELS.get(attribution, LABELS["uncertain"])
