import json
import os
import re

from groq import Groq

DETECTION_PROMPT = """You are an AI content detection expert. Analyze the following text and determine whether it was written by a human or generated by AI.

Consider factors like:
- Vocabulary diversity and word choice patterns
- Sentence rhythm and length variation
- Presence of personal voice, idiosyncrasies, or digressions
- Emotional depth and authenticity
- Stylistic consistency versus unnatural uniformity

Return your assessment as a JSON object with exactly these keys:
- "score": a number from 0.0 to 1.0 where 0.0 means "definitely AI-generated" and 1.0 means "definitely human-written"
- "reason": a brief explanation (1-3 sentences) of what informed your assessment

Respond with ONLY the JSON object, no other text."""


def classify_text(text: str) -> tuple[float, str]:
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return (0.5, "LLM signal unavailable: GROQ_API_KEY not set")

    client = Groq(api_key=api_key)

    try:
        response = client.chat.completions.create(
            messages=[
                {"role": "system", "content": DETECTION_PROMPT},
                {"role": "user", "content": text},
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.0,
            max_completion_tokens=256,
        )
        raw = response.choices[0].message.content or ""
        return _parse_response(raw, text)
    except Exception as e:
        return (0.5, f"LLM signal unavailable: {e}")


def _parse_response(raw: str, text: str) -> tuple[float, str]:
    raw = raw.strip()
    json_match = re.search(r"\{.*\}", raw, re.DOTALL)
    if json_match:
        raw = json_match.group(0)

    try:
        data = json.loads(raw)
        score = float(data.get("score", 0.5))
        reason = str(data.get("reason", "No reason provided"))
    except (json.JSONDecodeError, ValueError, TypeError):
        return (0.5, "LLM signal unavailable: could not parse model response")

    score = max(0.0, min(1.0, score))
    return (score, reason)
